# spring:
#  datasource:
#    url: jdbc:mysql://localhost/modules?useSSL=false
#    username: root
#    password: pa55w0rd
#    driver-class-name: com.mysql.jdbc.Driver

spring:
  datasource:
    name: modules
    platform: h2
  h2:
    console:
      enabled: true
      path: /console

pvdata:
  inverters: Inverter_List_Full_Data.csv
  modules: PV_Module_List_Full_Data.csv
