DROP TABLE IF EXISTS inverters;

CREATE TABLE `inverters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ManufacturerName` text,
  `ModelNumber` text,
  `Description` text,
  `PowerRatingContinuous` double,
  `NominalVoltage` text,
  `WeightedEfficiency` double,
  `UL1741SupplementACertification` text,
  `FirmwareVersionTested` text,
  `BuiltInMeter` text,
  `Microinverter` text,
  `Notes` text,
  `NightTareLoss` double,
  `PowerRatingContinuous40degC` double,
  `NightTareLoss40degC` double,
  `VoltageMinimum` double,
  `VoltageNominal` double,
  `VoltageMaximum` double,
  `PowerLevel10` double,
  `PowerLevel20` double,
  `PowerLevel30` double,
  `PowerLevel50` double,
  `PowerLevel75` double,
  `PowerLevel100` double,
  `EfficiencyVmin10` double,
  `EfficiencyVmin20` double,
  `EfficiencyVmin30` double,
  `EfficiencyVmin50` double,
  `EfficiencyVmin75` double,
  `EfficiencyVmin100` double,
  `EfficiencyVmin` double,
  `EfficiencyVnom10` double,
  `EfficiencyVnom20` double,
  `EfficiencyVnom30` double,
  `EfficiencyVnom50` double,
  `EfficiencyVnom75` double,
  `EfficiencyVnom100` double,
  `EfficiencyVnom` double,
  `EfficiencyVmax10` double,
  `EfficiencyVmax20` double,
  `EfficiencyVmax30` double,
  `EfficiencyVmax50` double,
  `EfficiencyVmax75` double,
  `EfficiencyVmax100` double,
  `EfficiencyVmax` double,
  `SortOrder` text,
  `CECListingDate` text,
  `LastUpdate` text,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS modules;

CREATE TABLE `modules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Manufacturer` text,
  `ModelNumber` text,
  `Description` text,
  `BIPV` text,
  `NameplatePmax` double,
  `PTC` double,
  `Notes` text,
  `NameplateVpmax` double,
  `NameplateIpmax` double,
  `NameplateVoc` double,
  `NameplateIsc` double,
  `AverageNOCT` double,
  `betaVoc` double,
  `betaVpmax` double,
  `alphaIsc` double,
  `alphaIpmax` double,
  `gammaPmax` double,
  `VPmaxlow` double,
  `IPmaxlow` double,
  `VPmaxNOCT` double,
  `IPmaxNOCT` double,
  `ShortSide` double,
  `LongSide` double,
  `GeometricMultiplier` text,
  `ApertureArea` double,
  `NumberCellsSeries` double,
  `NumberCellsParallel` double,
  `Type` text,
  `Family` text,
  `Technology` text,
  `P2Pref` double,
  `PercentNonlin` text,
  `a_ref` text,
  `I_o_ref` text,
  `I_L_ref` text,
  `R_s_ref` text,
  `R_sh_ref` text,
  `delta` text,
  `I_sc_adj` text,
  `Time` text,
  `Version` text,
  `Mounting` text,
  `LastUpdate` text,
  `CECListingDate` text,
  PRIMARY KEY (id)
);
